version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=oficina
      - POSTGRES_USER=oficinauser
      - POSTGRES_PASSWORD=oficinapassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oficinauser"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: oficina-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    # Se preferir, pode passar configs do Spring aqui por env também

volumes:
  postgres-data: