apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: oficina
type: Opaque
stringData:
  JWT_SECRET_BASE64: "QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVo0NTY3ODkwQUJDREVG"
  SECURITY_SEED_ADMIN_PASSWORD: "admin123"
  NEW_RELIC_LICENSE_KEY: "6511512713fd2de45bffcf65c5bdecb01c38NRAL"
  NEW_RELIC_API_KEY: "aa05b6be5835d4d70c0366e2245bce53bee9NRAL"
