apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: oficina
type: Opaque
stringData:
  JWT_SECRET_BASE64: "QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVo0NTY3ODkwQUJDREVG"
  SECURITY_SEED_ADMIN_PASSWORD: "admin123"
