apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: oficina
data:
  SPRING_PROFILES_ACTIVE: "prod"
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  JWT_ISSUER: "tech-challenge-mecanica-api"
  JWT_ACCESS_TOKEN_MINUTES: "15"
  SECURITY_SEED_ENABLED: "true"
  SECURITY_SEED_ADMIN_EMAIL: "admin@oficina.local"
  NEW_RELIC_ENABLED: "true"
  NEW_RELIC_APP_NAME: "tech-challenge-mecanica-k8s"
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
  NEW_RELIC_METRICS_ENABLED: "false"
  NEW_RELIC_ACCOUNT_ID: "8463371"
