apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: oficina
data:
  SPRING_PROFILES_ACTIVE: "prod"
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  JWT_ISSUER: "tech-challenge-mecanica-api"
  JWT_ACCESS_TOKEN_MINUTES: "15"
  SECURITY_SEED_ENABLED: "true"
  SECURITY_SEED_ADMIN_EMAIL: "admin@oficina.local"
