apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-bundle-nrk8s-agent-controlplane
  namespace: oficina
data:
  newrelic-infra.yml: |
    # This is the configuration file for the infrastructure agent. See:
    # https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/
    custom_attributes:
      clusterName: oficina-docker
    http_server_enabled: true
    http_server_port: 8001
    is_forward_only: false
